export const BLOG_ERROR = {
  POST_NOT_FOUND: 'BLOG_ERROR_POST_NOT_FOUND',
  SLUG_EXISTS: 'BLOG_ERROR_SLUG_EXISTS',
  CATEGORY_NOT_FOUND: 'BLOG_ERROR_CATEGORY_NOT_FOUND',
  CATEGORY_HAS_CHILDREN: 'BLOG_ERROR_CATEGORY_HAS_CHILDREN',
  TAG_NOT_FOUND: 'BLOG_ERROR_TAG_NOT_FOUND',
  COMMENT_NOT_FOUND: 'BLOG_ERROR_COMMENT_NOT_FOUND',
  POST_NOT_DELETED: 'BLOG_ERROR_POST_NOT_DELETED',
  POST_ALREADY_PUBLISHED: 'BLOG_ERROR_POST_ALREADY_PUBLISHED',
  POST_NOT_PUBLISHED: 'BLOG_ERROR_POST_NOT_PUBLISHED',
} as const;
